-- CreateTable
CREATE TABLE `permissao_recursos` (
    `id` VARCHAR(191) NOT NULL,
    `perfil` ENUM('DEV', 'SUP', 'ADM', 'USR', 'GAB_ASC') NOT NULL,
    `recurso` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `permissao_recursos_perfil_recurso_key`(`perfil`, `recurso`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


-- Dados iniciais: padrão de acesso de cada perfil (editável na tela de permissões)
INSERT INTO `permissao_recursos` (`id`, `perfil`, `recurso`) VALUES
  (UUID(), 'DEV', 'painel_inicial'),
  (UUID(), 'DEV', 'processos'),
  (UUID(), 'DEV', 'perfil'),
  (UUID(), 'DEV', 'dashboard_admissibilidade'),
  (UUID(), 'DEV', 'relatorios'),
  (UUID(), 'DEV', 'admissibilidade_decidir'),
  (UUID(), 'DEV', 'importar'),
  (UUID(), 'DEV', 'publicacoes'),
  (UUID(), 'DEV', 'reunioes'),
  (UUID(), 'DEV', 'usuarios'),
  (UUID(), 'DEV', 'unidades'),
  (UUID(), 'DEV', 'subprefeituras'),
  (UUID(), 'DEV', 'alvaras'),
  (UUID(), 'DEV', 'pareceres'),
  (UUID(), 'DEV', 'categorias'),
  (UUID(), 'DEV', 'motivos_inadmissao'),
  (UUID(), 'DEV', 'pedidos'),
  (UUID(), 'DEV', 'envio_relatorios'),
  (UUID(), 'ADM', 'painel_inicial'),
  (UUID(), 'ADM', 'processos'),
  (UUID(), 'ADM', 'perfil'),
  (UUID(), 'ADM', 'admissibilidade_decidir'),
  (UUID(), 'ADM', 'importar'),
  (UUID(), 'ADM', 'publicacoes'),
  (UUID(), 'ADM', 'reunioes'),
  (UUID(), 'ADM', 'usuarios'),
  (UUID(), 'ADM', 'unidades'),
  (UUID(), 'ADM', 'subprefeituras'),
  (UUID(), 'ADM', 'alvaras'),
  (UUID(), 'ADM', 'pareceres'),
  (UUID(), 'ADM', 'categorias'),
  (UUID(), 'ADM', 'motivos_inadmissao'),
  (UUID(), 'ADM', 'pedidos'),
  (UUID(), 'ADM', 'dashboard_admissibilidade'),
  (UUID(), 'ADM', 'relatorios'),
  (UUID(), 'SUP', 'painel_inicial'),
  (UUID(), 'SUP', 'processos'),
  (UUID(), 'SUP', 'perfil'),
  (UUID(), 'SUP', 'admissibilidade_decidir'),
  (UUID(), 'SUP', 'importar'),
  (UUID(), 'SUP', 'publicacoes'),
  (UUID(), 'SUP', 'reunioes'),
  (UUID(), 'SUP', 'usuarios'),
  (UUID(), 'SUP', 'unidades'),
  (UUID(), 'SUP', 'subprefeituras'),
  (UUID(), 'SUP', 'alvaras'),
  (UUID(), 'SUP', 'pareceres'),
  (UUID(), 'SUP', 'categorias'),
  (UUID(), 'SUP', 'motivos_inadmissao'),
  (UUID(), 'SUP', 'pedidos'),
  (UUID(), 'USR', 'painel_inicial'),
  (UUID(), 'USR', 'processos'),
  (UUID(), 'USR', 'perfil'),
  (UUID(), 'GAB_ASC', 'painel_inicial'),
  (UUID(), 'GAB_ASC', 'perfil'),
  (UUID(), 'GAB_ASC', 'dashboard_admissibilidade'),
  (UUID(), 'GAB_ASC', 'relatorios');
